// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/lionellc/fusion-gate/internal/config"
	"github.com/lionellc/fusion-gate/internal/handler"
	"github.com/lionellc/fusion-gate/internal/infra/db"
	"github.com/lionellc/fusion-gate/internal/infra/redis"
)

// Injectors from wire.go:

func wireApp(cfg *config.Config) (*gin.Engine, func(), error) {
	dbDB, cleanup, err := db.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	redisClient, cleanup2, err := redis.NewRedisClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engine := handler.NewRouter(dbDB, redisClient)
	return engine, func() {
		cleanup2()
		cleanup()
	}, nil
}
