// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/lionellc/fusion-gate/internal/config"
	service2 "github.com/lionellc/fusion-gate/internal/domain/apikey/service"
	service3 "github.com/lionellc/fusion-gate/internal/domain/channel/service"
	"github.com/lionellc/fusion-gate/internal/domain/user/service"
	"github.com/lionellc/fusion-gate/internal/handler"
	"github.com/lionellc/fusion-gate/internal/infra/db"
	"github.com/lionellc/fusion-gate/internal/infra/logger"
	"github.com/lionellc/fusion-gate/internal/infra/persistence"
	"github.com/lionellc/fusion-gate/internal/infra/redis"
)

// Injectors from wire.go:

func wireApp(cfg *config.Config) (*gin.Engine, func(), error) {
	dbDB, cleanup, err := db.NewDB(cfg)
	if err != nil {
		return nil, nil, err
	}
	userRepo := persistence.NewUserRepo(dbDB)
	authService := service.NewAuthService(cfg, userRepo)
	userHandler := handler.NewUserHandler(authService)
	apiKeyRepo := persistence.NewAPIKeyRepo(dbDB)
	apiKeyService := service2.NewAPIKeyService(apiKeyRepo)
	apiKeyHandler := handler.NewAPIKeyHandler(apiKeyService)
	channelRepo := persistence.NewChannelRepo(dbDB)
	slogLogger := logger.NewLogger()
	healthCheckService := service3.NewHealthCheckService(channelRepo, slogLogger)
	channelService := service3.NewChannelService(channelRepo, healthCheckService)
	channelHandler := handler.NewChannelHandler(channelService)
	handlerHandler := handler.NewHandler(userHandler, apiKeyHandler, channelHandler)
	redisClient, cleanup2, err := redis.NewRedisClient(cfg)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	engine := handler.NewRouter(handlerHandler, redisClient)
	return engine, func() {
		cleanup2()
		cleanup()
	}, nil
}
